name: grad2live_login
description: A new Flutter application.
publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_signin_button: ^1.0.0
  dropdownfield: 1.0.0
  datetime_picker_formfield: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
     - images/
  fonts:
  - family: Bebas Neue
    fonts:
      - asset: fonts/BebasNeue-Regular.ttf
